
# solver extra for last version of wxHaskell
resolver: lts-11.9

# for stability
packages:
- .
- wxHaskell/wx
- wxHaskell/wxc
- wxHaskell/wxcore
- wxHaskell/wxdirect
- src/subprojects/hasdoc-gen


# extra deps in versions run on current lts
extra-deps: 
- containers-0.5.11.0
- unordered-containers-0.2.9.0
- Cabal-2.4.1.0
- process-1.4.3.0
- app-settings-0.2.0.12
- open-browser-0.2.1.0
- directory-1.3.0.2
- executable-path-0.0.3.1
- pandoc-2.6
- HsYAML-0.1.1.3
- haddock-library-1.7.0
- hslua-1.0.2
- hslua-module-text-0.2.0
- ipynb-0.1
- pandoc-types-1.17.5.4
- skylighting-0.7.6
- skylighting-core-0.7.6
- texmath-0.11.2
- text-1.2.3.1
- blaze-html-0.9.1.1
- shakespeare-2.0.20
- filepath-1.4.2.1
- http-types-0.12.3
- ini-0.4.1

# line for installing helpful addons in Visual Studio Code without incompatiblities of Cabal versions
#allow-newer: true
