RunWiz: Run wizard
RunQuiz: Run Quiz
LabelRunWiz: Place for overthinking and describing new project with the possibility of writing to system and printing
LabelQuizWiz: Try, whenever you fluctuate between sequential and iterative approach

ProgramMenu: &Program
SaveStateMenu: &Save state  S
SaveStateMenuHelp: saves informations from the current session
LoadStateMenu: &Load State  L
LoadStateMenuHelp: loads saved state informations
LoadFilesExt: hasdoc files
LoadImportedFilesExt: html files
ImportFromFileMenu: &Import from file  I 
ImportFromFileMenuHelp: imports informations into wizard from saved html file
QuitMenu: &Quit  Q
QuitMenuHelp: closes application
OptionsMenu: &Options
SettingsMenu: &Settings  T
SettingsMenuHelp: creates new window with settings
AboutMenu: &About Hasdoc
AuthorMenu: &About authors
AuthorMenuHelp: contains informations about authors
HomepageMenu: &Homepage  W
HomepageMenuHelp: opens website with default browser
IssuesMenu: &Issues  B
IssuesMenuHelp: opens website about issues and ideas of application with default browser
ToolsMenu: &Tools
ToolsMenuHelp: contains list of used programming languages, editors, libraries
TipsMenu: &Tips
TipsMenuHelp: contains list of other ideas for creating new project
DocMenu: &Documentation  D
DocMenuHelp: FAQ
