RunWiz: Run wizard
RunQuiz: Run Quiz
LabelRunWiz: Place for overthinking and describing new project with the possibility of writing to system and printing
LabelQuizWiz: Try, whenever you fluctuate between sequential and iterative approach

ProgramMenu: &Program
SaveStateMenu: &Save state  Ctrl+S
SaveStateMenuHelp: saves informations from the current session
LoadStateMenu: &Load State  Ctrl+L
LoadStateMenuHelp: loads saved state informations
LoadFilesExt: hasdoc files
ImportFromFileMenu: &Import from file  Ctrl+I 
ImportFromFileMenuHelp: imports informations into wizard from saved pdf file
QuitMenu: &Quit  Ctrl+E
QuitMenuHelp: closes application
OptionsMenu: &Options
SettingsMenu: &Settings  Ctrl+U
SettingsMenuHelp: creates new window with settings
AboutMenu: &About Hasdoc
AuthorMenu: &About authors  Ctrl+A
AuthorMenuHelp: contains informations about authors
HomepageMenu: &Homepage  Ctrl+H
HomepageMenuHelp: opens website with default browser
IssuesMenu: &Issues  Ctrl+F
IssuesMenuHelp: opens website about issues and ideas of application with default browser
ToolsMenu: &Tools  Ctrl+T
ToolsMenuHelp: contains list of used programming languages, editors, libraries
TipsMenu: &Tips  Ctrl+P
TipsMenuHelp: contains list of other ideas for creating new project
DocMenu: &Documentation  Ctrl+D
DocMenuHelp: FAQ
