RunWiz: Uruchom wizarda
RunQuiz: Uruchom Quiz
LabelRunWiz: Miejsce na przemyślanie i opisywanie przyszłego projektu wraz z możliwością zapisu i drukowania
LabelQuizWiz: Spróbuj, jeśli wahasz się między podejściem sekwencyjnym, a iteracyjnym

ProgramMenu: Program
SaveStateMenu: Zapisz stan  S
SaveStateMenuHelp: zapisuje z bieżącej sesji informacje
LoadStateMenu: Wczytaj stan  L
LoadStateMenuHelp: wczytuje zapisaną wcześniej sesję
LoadFilesExt: Pliki hasdoc
LoadImportedFilesExt: pliki html
ImportFromFileMenu: Importuj z pliku  I 
ImportFromFileMenuHelp: importuje treści do wizarda z wygenerowanego wcześniej pliku (domyślnie z formatem *.pdf)
QuitMenu: Zakończ  Q
QuitMenuHelp: zamyka program
OptionsMenu: Opcje
SettingsMenu: Ustawienia  T
SettingsMenuHelp: generuje nowe okno z ustawieniami
AboutMenu: O programie
AuthorMenu: O autorze
AuthorMenuHelp: zawiera informacje o autorze programu
HomepageMenu: Strona domowa  W
HomepageMenuHelp: uruchomi odniesienie w domyślnej przeglądarce systemowej
IssuesMenu: Zgłoś błąd  B
IssuesMenuHelp: przekieruje na stronę, gdzie można zgłaszać błędy i pomysły dotyczące programu
ToolsMenu: Narzędzia 
ToolsMenuHelp: zawiera zbiór wykorzystywanych języków, narzędzi pomocniczych i bibliotek do stworzenia programu
TipsMenu: Wskazówki
TipsMenuHelp: zawiera listę dodatkowych pomysłów
DocMenu: Dokumentacja  D
DocMenuHelp: podręcznik elektroniczny o używaniu programu


SettWindow: Ustawienia
LangLabel: Wybierz jeden z poniższych języków. Po wyborze i dokonaniu zapisu wymagany jest restart programu.
LoadLabel: wczytaj zapisaną wcześniej sesję
ExeFiles: Pliki wykonywalne

ViewerLabel: Wybierz program zewnętrzny do przeglądania generowanego pliku pdf oraz do przeglądania dokumentacji w tym formacie. Jeśli nie chcesz obejrzeć pliku po jego wygenerowaniu, wybierz pierwszą opcję.

NoViewer: Brak
ExternalViewer: Program zewnętrzny
PrintDesc: Wybierz ustawienia dla okna drukowania. Można ten etap pominąć i nanieść zmiany w oknie generowanym przed etapem drukowania.
ScaleHint: Inaczej skala w procentach
OrientVChoice: Pionowa
OrientHChoice: Pozioma
ColourChoice: Kolor
GreyChoice: Skala szarości
BiOff: Wyłącz
ExtFilesLabel: Wybierz wyjściowe formaty danych poniżej. Zostaną one stworzone w wybranej ścieżce oraz katalogu o nazwie projektu. Pliki html oraz pdf są tworzone zawsze.
TemplatesLabel: Wybierz jeden z poniższych plików css dla wyjściowego pliku html, na podstawie którego powstanie plik pdf. Pierwsza opcja oznacza wydruk bez kolorów.
TemplatesList: Lista szablonów
PrintLabel: Domyślna drukarka
FormatLabel: Domyślny format
OrientLabel: Domyślna orientacja
ColourLabel: Domyślne uwzględnienie kolorów
BiPrintLabel: Tryb drukowania obustronnego
ResLabel: Domyślna rozdzielczość w %, np. 50, 100, 200 (Puste pole oznacza domyślną wartość 100 %)
MargingsLabel: Domyślne marginesy w mm, górnyMargines-prawyMargines-dolnyMargines-lewyMargines np. 25-25-25-25 (Puste pole oznacza użycie domyślnych ustawień)
ScopeLabel: Domyślny zakres drukowanych stron w formacie XX-XX lub XX, gdzie XX to dowolna liczba całkowita, np. 1-15, 23 (puste pole oznacza wszystkie strony)
LangTab: Języki
PreviewTab: Podgląd pliku
PrintingTab: Drukowanie
ExtOfFilesTab: Formaty plików
TemplatesSetTab: Szablony
SaveBtn: Zapisz
ResetBtn: Resetuj
CancelBtn: Anuluj

SaveLocation: Wybierz lokalizację dla zapisania postępu
NameSaveQuestion: Pod jaką nazwą chcesz zapisać postęp?
NameSave: Podaj nazwę pliku
StateNone: Brak stanu
WizardChangesWarning: Zmiany w wizardzie nie były wprowadzane
Save: Zapis
StateSave: Zapis stanu
ChosenPathSaveResult: Stan został pomyślnie zapisany w wybranej ścieżce

LoadState: Odczyt stanu
LoadStateResult: Stan został pomyślnie wczytany z wybranego pliku


ConfirmClose: Potwierdzenie
ConfirmCloseQuestion: Czy na pewno chcesz zamknąć aplikację?


ErrorBrowser: Błąd
ErrorBrowserDesc: Niemożliwe było połączenie ze stroną internetową. Sprawdź połączenie z siecią oraz wybór zainstalowanej domyślnej przeglądarki systemowej

ToolsDesc: Poniżej znajduje się lista bibliotek, języków programowania i narzędzi pomocniczych, które były używane podczas tworzenia aplikacji. Języki programowania - Haskell. Moduły - Pandoc, wxHaskell, AppSettings. IDE - Visual Studio Code. Notatniki - Kate. Pozostałe - GIMP, IconsFLOW (iconsflow.com)

AuthorsList: Autorzy
AuthorsDesc: Jagoda "juliagoda" Górska - Pasjonatka programowania od 5 lat. W dotychczasowych projektach znajdowały się takie języki programowania jak: Bash, C, C++, Haskell, Python, PHP. W trakcie nauki innych języków, języków obcych oraz sposobów nauki i metod pracy. Poniższa aplikacja jest odpowiedzią na pracę dyplomową, która dotyczyła analizy możliwości zastosowania języków czysto funkcyjnych w biznesie. Github - https://github.com/juliagoda
