RunWiz: Uruchom wizarda
RunQuiz: Uruchom Quiz
LabelRunWiz: Miejsce na przemyślanie i opisywanie przyszłego projektu wraz z możliwością zapisu i drukowania
LabelQuizWiz: Spróbuj, jeśli wahasz się między podejściem sekwencyjnym, a iteracyjnym

ProgramMenu: &Program
SaveStateMenu: &Zapisz stan  S
SaveStateMenuHelp: zapisuje z bieżącej sesji informacje
LoadStateMenu: &Wczytaj stan  L
LoadStateMenuHelp: wczytuje zapisaną wcześniej sesję
LoadFilesExt: Pliki hasdoc
LoadImportedFilesExt: pliki html
ImportFromFileMenu: &Importuj z pliku  I 
ImportFromFileMenuHelp: importuje treści do wizarda z wygenerowanego wcześniej pliku (domyślnie z formatem *.pdf)
QuitMenu: &Zakończ  Q
QuitMenuHelp: zamyka program
OptionsMenu: &Opcje
SettingsMenu: &Ustawienia  T
SettingsMenuHelp: generuje nowe okno z ustawieniami
AboutMenu: &O programie
AuthorMenu: &O autorze
AuthorMenuHelp: zawiera informacje o autorze programu
HomepageMenu: &Strona domowa  W
HomepageMenuHelp: uruchomi odniesienie w domyślnej przeglądarce systemowej
IssuesMenu: &Zgłoś błąd  B
IssuesMenuHelp: przekieruje na stronę, gdzie można zgłaszać błędy i pomysły dotyczące programu
ToolsMenu: &Narzędzia 
ToolsMenuHelp: zawiera zbiór wykorzystywanych języków, narzędzi pomocniczych i bibliotek do stworzenia programu
TipsMenu: &Wskazówki
TipsMenuHelp: zawiera listę dodatkowych pomysłów
DocMenu: &Dokumentacja  D
DocMenuHelp: podręcznik elektroniczny o używaniu programu
