RunWiz: Uruchom wizarda
RunQuiz: Uruchom Quiz
LabelRunWiz: Miejsce na przemyślanie i opisywanie przyszłego projektu wraz z możliwością zapisu i drukowania
LabelQuizWiz: Spróbuj, jeśli wahasz się między podejściem sekwencyjnym, a iteracyjnym

ProgramMenu: &Program
SaveStateMenu: &Zapisz stan  Ctrl+S
SaveStateMenuHelp: zapisuje z bieżącej sesji informacje
LoadStateMenu: &Wczytaj stan  Ctrl+L
LoadStateMenuHelp: wczytuje zapisaną wcześniej sesję
LoadFilesExt: Pliki pdf
ImportFromFileMenu: &Importuj z pliku  Ctrl+I 
ImportFromFileMenuHelp: importuje treści do wizarda z wygenerowanego wcześniej pliku (domyślnie z formatem *.pdf)
QuitMenu: &Zakończ  Ctrl+E
QuitMenuHelp: zamyka program
OptionsMenu: &Opcje
SettingsMenu: &Ustawienia  Ctrl+U
SettingsMenuHelp: generuje nowe okno z ustawieniami
AboutMenu: &O programie
AuthorMenu: &O autorze  Ctrl+A
AuthorMenuHelp: zawiera informacje o autorze programu
HomepageMenu: &Strona domowa  Ctrl+H
HomepageMenuHelp: uruchomi odniesienie w domyślnej przeglądarce systemowej
IssuesMenu: &Zgłoś błąd  Ctrl+F
IssuesMenuHelp: przekieruje na stronę, gdzie można zgłaszać błędy i pomysły dotyczące programu
ToolsMenu: &Narzędzia  Ctrl+T
ToolsMenuHelp: zawiera zbiór wykorzystywanych języków, narzędzi pomocniczych i bibliotek do stworzenia programu
TipsMenu: &Wskazówki  Ctrl+P
TipsMenuHelp: zawiera listę dodatkowych pomysłów
DocMenu: &Dokumentacja  Ctrl+D
DocMenuHelp: podręcznik elektroniczny o używaniu programu
