name:                hasdoc-gen
version:             1.0
github:              "juliagoda/hasdoc-gen"
license:             BSD3
author:              Jagoda "juliagoda" Górska <juliagoda.pl@protonmail.com>
maintainer:          Jagoda "juliagoda" Górska <juliagoda.pl@protonmail.com>
copyright:           (c) 2019 Jagoda "juliagoda" Górska

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/juliagoda/hasdoc-gen#readme>

dependencies:
- base >=4.4 && <4.11
- containers
- unordered-containers
- process
- pandoc
- HsYAML
- haddock-library
- hslua
- hslua-module-text
- ipynb
- pandoc-types
- skylighting
- skylighting-core
- texmath
- text
- blaze-html
- shakespeare
- monadplus
- app-settings
- directory
- bytestring
- ini
- tagsoup
- http-types
- binary
- wx
- wxcore

library:
  source-dirs: src
  
  
custom-setup:
  dependencies:
    - base
    - Cabal
    - directory
    - filepath

executables:
  hasdoc-gen:
    main:                HasdocGen.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-M2G
    - -Wall
    dependencies:
    - hasdoc-gen
