
resolver: lts-11.9
jobs: 2

packages:
- .
- wxHaskell/wx
- wxHaskell/wxc
- wxHaskell/wxcore
- wxHaskell/wxdirect


extra-deps: 
- containers-0.5.11.0
- unordered-containers-0.2.9.0
- Cabal-2.4.1.0
- process-1.4.3.0
- pandoc-2.6
- HsYAML-0.1.1.3
- haddock-library-1.7.0
- hslua-1.0.2
- hslua-module-text-0.2.0
- ipynb-0.1
- pandoc-types-1.17.5.4
- skylighting-0.7.6
- skylighting-core-0.7.6
- texmath-0.11.2
- text-1.2.3.1
- blaze-html-0.9.1.1
- shakespeare-2.0.20
- monadplus-1.4.2
- app-settings-0.2.0.12
- directory-1.3.0.2
- bytestring-0.10.8.2
- ini-0.4.1
- tagsoup-0.14.6
- http-types-0.12.3
#- pandoc-2.1.2
